/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TableRowComponent {
        /**
          * Cell contents
         */
        "cells": Array<string>;
        /**
          * Whether to render a header row or standard row
         */
        "isHeader": boolean;
    }
    interface TextComponent {
        /**
          * Determines the appearance of the text
         */
        "appearance": 'title' | 'paragraph' | 'link';
        /**
          * Determines the font size
         */
        "size": 's' | 'm' | 'l';
        /**
          * HTML tag to render as
         */
        "tag": string;
        /**
          * Whether the text will have dark or light colors
         */
        "theme": 'dark' | 'light';
    }
}
declare global {
    interface HTMLTableRowComponentElement extends Components.TableRowComponent, HTMLStencilElement {
    }
    var HTMLTableRowComponentElement: {
        prototype: HTMLTableRowComponentElement;
        new (): HTMLTableRowComponentElement;
    };
    interface HTMLTextComponentElement extends Components.TextComponent, HTMLStencilElement {
    }
    var HTMLTextComponentElement: {
        prototype: HTMLTextComponentElement;
        new (): HTMLTextComponentElement;
    };
    interface HTMLElementTagNameMap {
        "table-row-component": HTMLTableRowComponentElement;
        "text-component": HTMLTextComponentElement;
    }
}
declare namespace LocalJSX {
    interface TableRowComponent {
        /**
          * Cell contents
         */
        "cells": Array<string>;
        /**
          * Whether to render a header row or standard row
         */
        "isHeader"?: boolean;
    }
    interface TextComponent {
        /**
          * Determines the appearance of the text
         */
        "appearance"?: 'title' | 'paragraph' | 'link';
        /**
          * Determines the font size
         */
        "size"?: 's' | 'm' | 'l';
        /**
          * HTML tag to render as
         */
        "tag"?: string;
        /**
          * Whether the text will have dark or light colors
         */
        "theme"?: 'dark' | 'light';
    }
    interface IntrinsicElements {
        "table-row-component": TableRowComponent;
        "text-component": TextComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "table-row-component": LocalJSX.TableRowComponent & JSXBase.HTMLAttributes<HTMLTableRowComponentElement>;
            "text-component": LocalJSX.TextComponent & JSXBase.HTMLAttributes<HTMLTextComponentElement>;
        }
    }
}
